### ISSUE TITLE
How do I view metadata stored on ETCD 

### ISSUE THREAD

**Issue by skye95git** [milvus-io/milvus-docs#1327]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] asked MilMil.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

> Etcd is the metadata engine of the system, supporting the storage and access of the underlying metadata. 
> Etcd stores snapshots of meta information, such as collection Schema information, node status information, and checkpoint of message consumption.

What does the metadata here refer to?    

Is it the original data corresponding to the vector data?  

If yes, what is the difference between storing metadata in ETCD and in Postgres?  And how can I view metadata stored in ETCD by key?

**Comment by xiaofan-luan** [comment]
1. the metadata here refer to collection schemas, segment infos and role lease....
2.Not sure where this original data mean, but data usually separated to vector and scalar.
3. We are planing to store some of the meta into postgres,(plugin meta store) but etcd also necessary because we also used as service discovery. To inspect etcd data you can use etcdctl as a tool
