### ISSUE TITLE
Translate create_collection.md into CN

### ISSUE THREAD

**Issue by aFlyBird0** [milvus-io/milvus-docs#1500]
### Is your question answered elsewhere?

- [X] searched the existing issues.
- [X] read the [documentation](https://milvus.io/docs).

### What is your question?

I'm new here.

It seems like big translation work hasn't continued since last November. So, is it appropriate to translate the 2.0.x version of the document now?

If appropriate, I want to hvae a try. (Learning driven by tranlating and refering docs). 

Please check the translation of key positions of my future pr.

**Comment by claireyuw** [comment]
@aFlyBird0 Hi there, welcome to the Milvus Project! We appreciate your interest in contributing Chinese translation to Milvus documentation, though I should note that we have ceased to provide an official CN site due to limited resources. However, I believe that another contributor @soulteary shares your enthusiasm and already has an [ongoing initiative](https://github.com/milvus-io/milvus-docs/issues/1449) for Milvus CN docs translation. 

It would be super exciting to see you guys work together!🎉
