### ISSUE TITLE
[ERROR]: AWS EKS installation doc is confusing

### ISSUE THREAD

**Issue by jaime0815** [milvus-io/milvus-docs#1815]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Issue

![image](https://user-images.githubusercontent.com/4024711/194190178-6bfb4384-7ca5-4b23-81fd-346a2dffdb95.png)

[The installation needs to be clarified. ](https://milvus.io/docs/v2.1.x/eks.md)：
1. Add helm repo step
2. install should not use an upgrade command

**Comment by YiyunNi** [comment]
Fixed with PR #1816.

1.  Added the step of adding Milvus helm repo.
2. The command can actually install Milvus if there is no such instance. If there is such an instance, the command will upgrade Milvus.

FYI, we will fix the issue temporarily by adding the necessary steps. Later, this doc will go through an overhaul for better clarity.
