### ISSUE TITLE
2.0.0 Hello Milvus (example_code.md) - Add other languages

### ISSUE THREAD

**Issue by claireyuw** [milvus-io/milvus-docs#850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Topic

Add code in other available languages (Node.js and Go) in example.md.

### Type

how-to doc

**Comment by claireyuw** [comment]
@GuyKh Of course! @nameczz here can answer any questions you may have and provide further instructions if needed.

**Comment by GuyKh** [comment]
@nameczz I've actually just thought of creating a similar `hello_milvus.js` file to https://github.com/milvus-io/pymilvus/blob/master/examples/hello_milvus.py
and keep the instructions pretty much the same

**Comment by nameczz** [comment]
I saw your HelloMilvus.ts and i have some suggestions about it.
1. We need to load collection before vector search. Use loadCollectionSync is better. Check https://milvus.io/api-reference/node/v1.0.16/api%20reference/collection.html#loadcollection.
2. We need to use search instead of query.  You can check https://milvus.io/api-reference/node/v1.0.16/api%20reference/data.html for difference.
3. Could you please also create a pr for milvus-sdk-node. Then this link  https://raw.githubusercontent.com/milvus-io/milvus-sdk-node/main/example/MilvusHello.ts will working.

Thanks for your working :)

**Comment by nameczz** [comment]
@GuyKh  Now you created a pr in your forked repo. You need to create a pr in https://github.com/milvus-io/milvus-sdk-node.
Click New pull request, then click compare across forks, choose your forked repo and branch.
![image](https://user-images.githubusercontent.com/20559208/137440397-977e658c-a980-481a-bc19-b0d43ff2b9c6.png)

**Comment by claireyuw** [comment]
@GuyKh Thank you for your contribution! Once you've made the changes instructed by @nameczz, can you put the "Run Milvus with Node.js" content in a new file and name it `example_code_node.md`? You can leave the current `example_code.md` as is.

And in the front-matter of the new page, please put in below:
```
---
id: example_code_node.md
title: Run Milvus with Node.js
label: Node.js
order: 1
group: example
summary: Get started with Milvus faster using this Node.js example code.
---
```

Thank you!
